# Generated by Django 3.2.18 on 2023-02-18 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20230218_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('adventure', 'Adventure'), ('nature', 'Nature'), ('landscape', 'Landscape'), ('wildlife', 'Wildlife'), ('street', 'Street'), ('architecture', 'Architecture')], default='adventure', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='featured post'),
        ),
    ]
