# Generated by Django 3.2.18 on 2023-02-26 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_taggedpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='draft',
            field=models.IntegerField(choices=[('0', 'Save as draft'), ('1', 'Publish now')], default=1),
        ),
    ]
