# Generated by Django 3.2.18 on 2023-02-27 18:12

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='CONST.PLACEHOLDER', max_length=255, verbose_name='image'),
        ),
    ]
