# Generated by Django 3.2.18 on 2023-03-22 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_alter_post_excerpt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('adventure', 'Adventure'), ('travel', 'Travel'), ('nature', 'Nature'), ('landscape', 'Landscape'), ('aerial', 'Aerial'), ('wildlife', 'Wildlife'), ('street', 'Street'), ('architecture', 'Architecture')], max_length=20),
        ),
    ]
